### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-details-changelog#1]
It may be useful to add directions for this component:

This is an example to expand it top:

https://creativemarket.com/studio2am/5636347-Whole-Shop-Bundle-80-OFF
![show all component](https://user-images.githubusercontent.com/5861215/108182764-a9106380-7109-11eb-90fa-d1cc65237d17.gif)

**Comment by claudia-romano** [comment]
Hi Dario, you should be able to do that using the Read More component:
https://codyhouse.co/ds/components/app/read-more

Cheers!
